# Generated by Django 6.0.2 on 2026-02-27 12:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(help_text='Description of the habit task', max_length=255)),
                ('periodicity', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='How often the habit should be completed', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the habit was created')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the habit is currently being tracked')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the habit was completed')),
                ('habit', models.ForeignKey(help_text='The habit that was completed', on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='habits.habit')),
            ],
            options={
                'verbose_name': 'Habit Completion',
                'verbose_name_plural': 'Habit Completions',
                'ordering': ['-completed_at'],
            },
        ),
    ]
